### ISSUE TITLE
Online Export Tool Issues

### ISSUE THREAD

**Issue by Dealtz** [run27017/nested-json-to-table#2]
The online export tool can only recognize json data below:
[
  {
    "a": 1,
    "b": 2
  },
  {
    "a": 3,
    "b": 4
  }
]
But I have some data in this form, just like you give in readme.md:
[
  {
    a: 1,
    b: 2
  },
  {
    a: 3,
    b: 4
  }
]
The online exort tool can not recognize it, it shows that "JSON语法错误(SyntaxError: Unexpected token a in JSON at position 10)"
Can you solve it?
或者我只能在本地跑你的程序, 就像在readme.md里一样,然后把这部分数据作为const变量了吗?

**Comment by run27017** [comment]
你好。第二个数据不是合法的 JSON 啊。如果你是用的那个在线网站的话，我目前只考虑了支持合法的 JSON. 你可以尝试下面的手法将一般的 JS 对象转成  JSON：

```
const data = [
{
a: 1,
b: 2
},
{
a: 3,
b: 4
}
]
JSON.stringify(data)
```

**Comment by Dealtz** [comment]
> 你好。第二个数据不是合法的 JSON 啊。如果你是用的那个在线网站的话，我目前只考虑了支持合法的 JSON. 你可以尝试下面的手法将一般的 JS 对象转成 JSON：
> 
> ```
> const data = [
> {
> a: 1,
> b: 2
> },
> {
> a: 3,
> b: 4
> }
> ]
> JSON.stringify(data)
> ```

抱歉开issue的时候我对Json格式没有太多了解，直接从您的readme里[0.2.1. 简单格式](https://github.com/run27017/nested-json-to-table#021-%E7%AE%80%E5%8D%95%E6%A0%BC%E5%BC%8F)直接粘到网页工具，发现报错，所以开的issue。
